{
    "identifier": "CVE-2009-0669",
    "summary": "Zope Object Database (ZODB) before 3.8.2, when certain Zope Enterprise Objects (ZEO) database sharing is enabled, allows remote attackers to bypass authentication via vectors involving the ZEO network protocol.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-33166"
        }
    ],
    "vulnerable_packages": [],
    "resolved_packages": [
        "pkg:pypi/zodb@5.4.0",
        "pkg:pypi/zodb@5.5.1",
        "pkg:pypi/zodb@5.0.0a4",
        "pkg:pypi/zodb@5.2.0",
        "pkg:pypi/zodb@4.3.1",
        "pkg:pypi/zodb@4.0.0b2",
        "pkg:pypi/zodb@5.0.1",
        "pkg:pypi/zodb@5.0.0a6",
        "pkg:pypi/zodb@4.0.0a1",
        "pkg:pypi/zodb@4.4.4",
        "pkg:pypi/zodb@5.0.0a1",
        "pkg:pypi/zodb@4.2.0b1",
        "pkg:pypi/zodb@5.2.2",
        "pkg:pypi/zodb@4.4.0",
        "pkg:pypi/zodb@5.2.3",
        "pkg:pypi/zodb@5.6.0",
        "pkg:pypi/zodb@5.0.0a5",
        "pkg:pypi/zodb@5.0.0",
        "pkg:pypi/zodb@4.4.2",
        "pkg:pypi/zodb@5.0.0a2",
        "pkg:pypi/zodb@5.0.0b1",
        "pkg:pypi/zodb@5.5.0",
        "pkg:pypi/zodb@5.3.0",
        "pkg:pypi/zodb@4.2.0",
        "pkg:pypi/zodb@4.1.0",
        "pkg:pypi/zodb@5.1.0",
        "pkg:pypi/zodb@5.0.0a3",
        "pkg:pypi/zodb@4.4.5",
        "pkg:pypi/zodb@5.1.1",
        "pkg:pypi/zodb@4.4.1",
        "pkg:pypi/zodb@4.0.0",
        "pkg:pypi/zodb@4.0.0a3",
        "pkg:pypi/zodb@4.4.3",
        "pkg:pypi/zodb@4.3.0",
        "pkg:pypi/zodb@4.0.1",
        "pkg:pypi/zodb@4.0.0b3",
        "pkg:pypi/zodb@5.2.4",
        "pkg:pypi/zodb@5.2.1",
        "pkg:pypi/zodb@4.0.0a2",
        "pkg:pypi/zodb@4.0.0b1",
        "pkg:pypi/zodb@4.0.0a4"
    ]
}