{
    "identifier": "CVE-2014-1928",
    "summary": "The shell_quote function in python-gnupg 0.3.5 does not properly escape characters, which allows context-dependent attackers to execute arbitrary code via shell metacharacters in unspecified vectors, as demonstrated using \"\\\" (backslash) characters to form multi-command sequences, a different vulnerability than CVE-2014-1927.  NOTE: this vulnerability exists because of an incomplete fix for CVE-2013-7323.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-35534"
        }
    ],
    "vulnerable_packages": [],
    "resolved_packages": [
        "pkg:pypi/gnupg@1.1.2-2-g543d478-dirty",
        "pkg:pypi/gnupg@1.2.1",
        "pkg:pypi/gnupg@1.3.2",
        "pkg:pypi/gnupg@1.1.6",
        "pkg:pypi/gnupg@1.1.5",
        "pkg:pypi/gnupg@2.0.0",
        "pkg:pypi/gnupg@1.3.3",
        "pkg:pypi/gnupg@1.2.6",
        "pkg:pypi/gnupg@1.1.2-2-g543d478",
        "pkg:pypi/gnupg@1.2.4",
        "pkg:pypi/gnupg@2.3.0",
        "pkg:pypi/gnupg@2.1.0",
        "pkg:pypi/gnupg@1.1.7",
        "pkg:pypi/gnupg@2.0.1",
        "pkg:pypi/gnupg@1.1.4",
        "pkg:pypi/gnupg@1.1.3-1-gc837b73",
        "pkg:pypi/gnupg@2.3.1",
        "pkg:pypi/gnupg@1.3.1",
        "pkg:pypi/gnupg@2.0.2",
        "pkg:pypi/gnupg@1.2.0",
        "pkg:pypi/gnupg@1.1.3",
        "pkg:pypi/gnupg@1.2.5",
        "pkg:pypi/gnupg@1.3.0",
        "pkg:pypi/gnupg@1.1.0-2-g555364d-dirty",
        "pkg:pypi/gnupg@1.4.0",
        "pkg:pypi/gnupg@1.2.2",
        "pkg:pypi/gnupg@1.2.3",
        "pkg:pypi/gnupg@1.1.8",
        "pkg:pypi/gnupg@2.2.0"
    ]
}