{
    "identifier": "CVE-2019-1010083",
    "summary": "The Pallets Project Flask before 1.0 is affected by: unexpected memory usage. The impact is: denial of service. The attack vector is: crafted encoded JSON data. The fixed version is: 1. See: CVE-2019-1010083. (NOTE: this may overlap CVE-2018-1000656.)",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-38654"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/flask@0.10.1",
        "pkg:pypi/flask@0.8",
        "pkg:pypi/flask@0.12.5",
        "pkg:pypi/flask@0.3.1",
        "pkg:pypi/flask@0.5.1",
        "pkg:pypi/flask@0.3",
        "pkg:pypi/flask@0.5.2",
        "pkg:pypi/flask@0.7",
        "pkg:pypi/flask@0.5",
        "pkg:pypi/flask@0.1",
        "pkg:pypi/flask@0.12.3",
        "pkg:pypi/flask@0.12.1",
        "pkg:pypi/flask@0.4",
        "pkg:pypi/flask@0.6",
        "pkg:pypi/flask@0.7.2",
        "pkg:pypi/flask@0.7.1",
        "pkg:pypi/flask@0.9",
        "pkg:pypi/flask@0.12.4",
        "pkg:pypi/flask@0.2",
        "pkg:pypi/flask@0.6.1",
        "pkg:pypi/flask@0.11.1",
        "pkg:pypi/flask@0.8.1",
        "pkg:pypi/flask@0.11",
        "pkg:pypi/flask@0.12",
        "pkg:pypi/flask@0.12.2",
        "pkg:pypi/flask@0.10"
    ],
    "resolved_packages": [
        "pkg:pypi/flask@1.0.2",
        "pkg:pypi/flask@1.0.3",
        "pkg:pypi/flask@1.0",
        "pkg:pypi/flask@1.1.2",
        "pkg:pypi/flask@1.1.1",
        "pkg:pypi/flask@1.1.0",
        "pkg:pypi/flask@1.0.4",
        "pkg:pypi/flask@1.0.1"
    ]
}