{
    "identifier": "VULCODE-2020-09-26 12:44:11.453667",
    "summary": "aiohttp-auth-autz before 0.2.0 isn't correctly checking the user_id in acl middleware, leading to a possible permission escalation.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-32971"
        }
    ],
    "vulnerable_packages": [],
    "resolved_packages": [
        "pkg:pypi/aiohttp-auth-autz@0.2.2",
        "pkg:pypi/aiohttp-auth-autz@0.2.0",
        "pkg:pypi/aiohttp-auth-autz@0.2.1"
    ]
}