{
    "identifier": "VULCODE-2020-09-26 12:44:07.846701",
    "summary": "The server of aioftp 0.15.0 uses explicit mapping of available commands for security reasons.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-38045"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/aioftp@0.0.1",
        "pkg:pypi/aioftp@0.3.0",
        "pkg:pypi/aioftp@0.6.0",
        "pkg:pypi/aioftp@0.1.1",
        "pkg:pypi/aioftp@0.3.1",
        "pkg:pypi/aioftp@0.1.6",
        "pkg:pypi/aioftp@0.6.2",
        "pkg:pypi/aioftp@0.8.0",
        "pkg:pypi/aioftp@0.6.1",
        "pkg:pypi/aioftp@0.11.0",
        "pkg:pypi/aioftp@0.1.4",
        "pkg:pypi/aioftp@0.1.3",
        "pkg:pypi/aioftp@0.5.0",
        "pkg:pypi/aioftp@0.7.0",
        "pkg:pypi/aioftp@0.1.2",
        "pkg:pypi/aioftp@0.1.0",
        "pkg:pypi/aioftp@0.6.3",
        "pkg:pypi/aioftp@0.9.0",
        "pkg:pypi/aioftp@0.4.0",
        "pkg:pypi/aioftp@0.4.1",
        "pkg:pypi/aioftp@0.2.0",
        "pkg:pypi/aioftp@0.1.7",
        "pkg:pypi/aioftp@0.10.0",
        "pkg:pypi/aioftp@0.14.0",
        "pkg:pypi/aioftp@0.12.0",
        "pkg:pypi/aioftp@0.13.0",
        "pkg:pypi/aioftp@0.8.1",
        "pkg:pypi/aioftp@0.11.1",
        "pkg:pypi/aioftp@0.10.1",
        "pkg:pypi/aioftp@0.1.5"
    ],
    "resolved_packages": [
        "pkg:pypi/aioftp@0.16.1",
        "pkg:pypi/aioftp@0.16.0",
        "pkg:pypi/aioftp@0.17.2",
        "pkg:pypi/aioftp@0.17.0",
        "pkg:pypi/aioftp@0.15.0",
        "pkg:pypi/aioftp@0.18.0",
        "pkg:pypi/aioftp@0.17.1"
    ]
}