{
    "identifier": "VULCODE-2020-09-26 12:46:44.330613",
    "summary": "Django-hashid-field 3.1.1 fixes a security bug where comparison operators (gt, gte, lt, lte) would allow integer lookups regardless of ALLOW_INT_LOOKUP setting.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-37680"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/django-hashid-field@1.2.1",
        "pkg:pypi/django-hashid-field@2.0.0",
        "pkg:pypi/django-hashid-field@1.0.1",
        "pkg:pypi/django-hashid-field@2.1.1",
        "pkg:pypi/django-hashid-field@2.1.6",
        "pkg:pypi/django-hashid-field@2.1.5",
        "pkg:pypi/django-hashid-field@1.2.2",
        "pkg:pypi/django-hashid-field@1.1.0",
        "pkg:pypi/django-hashid-field@2.1.2",
        "pkg:pypi/django-hashid-field@3.0.0",
        "pkg:pypi/django-hashid-field@0.1.6",
        "pkg:pypi/django-hashid-field@2.1.4",
        "pkg:pypi/django-hashid-field@1.3.0",
        "pkg:pypi/django-hashid-field@1.2.0",
        "pkg:pypi/django-hashid-field@2.0.1",
        "pkg:pypi/django-hashid-field@1.0.0",
        "pkg:pypi/django-hashid-field@1.2.3",
        "pkg:pypi/django-hashid-field@2.1.0"
    ],
    "resolved_packages": [
        "pkg:pypi/django-hashid-field@3.1.3",
        "pkg:pypi/django-hashid-field@3.1.1",
        "pkg:pypi/django-hashid-field@3.1.2"
    ]
}