{
    "identifier": "VULCODE-2020-09-26 12:48:46.423438",
    "summary": "kytos 2019.1b3 change: Changed some dependencies versions in order to fix security bugs",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-37226"
        }
    ],
    "vulnerable_packages": [
        "pkg:pypi/kytos@2018.1b3.post2",
        "pkg:pypi/kytos@2018.1b1",
        "pkg:pypi/kytos@2018.1",
        "pkg:pypi/kytos@2019.1b2",
        "pkg:pypi/kytos@2017.1rc1",
        "pkg:pypi/kytos@2018.2b2",
        "pkg:pypi/kytos@2017.1b2.post1",
        "pkg:pypi/kytos@2018.2b1",
        "pkg:pypi/kytos@2017.2",
        "pkg:pypi/kytos@2018.2rc1",
        "pkg:pypi/kytos@2018.1rc1",
        "pkg:pypi/kytos@2018.2b3",
        "pkg:pypi/kytos@2017.1",
        "pkg:pypi/kytos@2017.1b2.post2",
        "pkg:pypi/kytos@2018.1b3.post1",
        "pkg:pypi/kytos@2018.1b3",
        "pkg:pypi/kytos@2017.2b2.post1",
        "pkg:pypi/kytos@2017.1b3",
        "pkg:pypi/kytos@2017.2rc1.post1",
        "pkg:pypi/kytos@2018.1b1.post1",
        "pkg:pypi/kytos@2017.2b1",
        "pkg:pypi/kytos@2018.2",
        "pkg:pypi/kytos@2018.1b2",
        "pkg:pypi/kytos@2019.1b1"
    ],
    "resolved_packages": [
        "pkg:pypi/kytos@2020.2b1",
        "pkg:pypi/kytos@2020.1",
        "pkg:pypi/kytos@2020.1rc1",
        "pkg:pypi/kytos@2020.1b2",
        "pkg:pypi/kytos@2020.1b1",
        "pkg:pypi/kytos@2019.2b2",
        "pkg:pypi/kytos@2019.2b3",
        "pkg:pypi/kytos@2019.2b1",
        "pkg:pypi/kytos@2019.1b3",
        "pkg:pypi/kytos@2019.2",
        "pkg:pypi/kytos@2019.1",
        "pkg:pypi/kytos@2019.1rc1",
        "pkg:pypi/kytos@2020.1b3",
        "pkg:pypi/kytos@2019.2rc1"
    ]
}