{
    "identifier": "VULCODE-2020-09-26 12:46:58.628795",
    "summary": "django-social-auth3 0.7.2 fixes a security hole - redirects via the next param are now properly sanitized to disallow redirecting to  external hosts.",
    "references": [
        {
            "url": "",
            "reference_id": "pyup.io-25791"
        }
    ],
    "vulnerable_packages": [],
    "resolved_packages": [
        "pkg:pypi/django-social-auth3@0.7.23",
        "pkg:pypi/django-social-auth3@0.7.21",
        "pkg:pypi/django-social-auth3@0.7.20",
        "pkg:pypi/django-social-auth3@0.7.22"
    ]
}